# Generated by Django 5.2.12 on 2026-05-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_title', models.CharField(blank=True, max_length=255, verbose_name='Вакансия')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('registration_address', models.TextField(verbose_name='Адрес прописки')),
                ('residence_address', models.TextField(verbose_name='Адрес проживания')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('education', models.CharField(max_length=255, verbose_name='Образование')),
                ('specialty', models.CharField(max_length=255, verbose_name='Специальность')),
                ('municipal_experience', models.CharField(blank=True, max_length=255, verbose_name='Стаж муниципальной службы')),
                ('work_experience', models.TextField(blank=True, verbose_name='Трудовая деятельность')),
                ('marital_status', models.CharField(choices=[('single', 'Холост/Не замужем'), ('married', 'Женат/Замужем'), ('divorced', 'Разведен(а)'), ('widowed', 'Вдовец/Вдова')], max_length=20, verbose_name='Семейное положение')),
                ('children', models.CharField(blank=True, max_length=255, verbose_name='Наличие детей')),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos/', verbose_name='Фото')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Резюме')),
                ('vacancy_source', models.TextField(blank=True, verbose_name='Откуда узнал(а)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
            ],
            options={
                'verbose_name': 'Заявка на вакансию',
                'verbose_name_plural': 'Заявки на вакансии',
            },
        ),
    ]
