# Generated by Django 5.2.12 on 2026-05-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('company', models.CharField(max_length=255, verbose_name='Компания/отдел')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('salary', models.CharField(max_length=255, verbose_name='Зарплата')),
                ('employment_type', models.CharField(blank=True, max_length=100, verbose_name='Тип занятости')),
                ('experience', models.CharField(blank=True, max_length=100, verbose_name='Опыт')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новая вакансия')),
                ('skills', models.TextField(blank=True, help_text='Каждый навык с новой строки', verbose_name='Навыки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
