# Generated by Django 5.2.12 on 2026-05-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_staffmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('info', 'Информация о тендерах'), ('results', 'Результаты тендеров'), ('rules', 'Правила тендеров')], max_length=20, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.FileField(upload_to='tenders/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
                'ordering': ['-created_at'],
            },
        ),
    ]
