# Generated by Django 5.2.14 on 2026-05-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_branch_remove_vacancy_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
