# Generated by Django 5.2.14 on 2026-05-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_staffmember_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Порядок'),
        ),
    ]
