# Generated by Django 5.2.14 on 2026-05-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_staffmember_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='surname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия'),
        ),
    ]
