# Generated by Django 5.2.14 on 2026-05-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_staffmember_name_alter_staffmember_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
