# Generated by Django 5.2.14 on 2026-05-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_jobtype_requiredexperience_workschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='show_on_honorboard',
            field=models.BooleanField(default=True, verbose_name='Показывать на доске почёта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='branch',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отдел'),
        ),
    ]
